---
name: HTML-StripScripts-Regex
version: 0.02
author:
  - 'Nick Cleaton <nick@cleaton.net>'
abstract: XSS filter using a regular expression
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  HTML::StripScripts: 1
  perl: 5.006001
configure_requires:
  Module::Build: 0.35
provides:
  HTML::StripScripts::Regex:
    file: lib/HTML/StripScripts/Regex.pm
    version: 0.02
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
